import type {
  RecordCodeDetailValue,
  RecordCodeSupportingHighlightValue,
} from "./record-code-types";

function highlight(
  id: string,
  sessionId: string,
  sessionTitle: string,
  speaker: string,
  location: string,
  excerpt: string,
): RecordCodeSupportingHighlightValue {
  return {
    excerpt,
    id,
    location,
    projectId: "project-1",
    projectName: "Test Project 1",
    sessionId,
    sessionTitle,
    speaker,
  };
}

export const recordCodeDetails: RecordCodeDetailValue[] = [
  {
    acceptedHighlightCount: 12,
    description: "Labels and navigation language did not match participant expectations.",
    eligibleSessionCount: 4,
    evidenceGroups: [
      {
        highlights: [
          highlight(
            "highlight-navigation-1",
            "session-checkout",
            "Checkout usability test",
            "Robert",
            "3:28",
            "I tab to the navigation, then through several utility buttons before I reach the table.",
          ),
          highlight(
            "highlight-navigation-2",
            "session-checkout",
            "Checkout usability test",
            "Maya Chen",
            "13:51",
            "What label would help?",
          ),
        ],
        sessionId: "session-checkout",
        sessionTitle: "Checkout usability test",
      },
      {
        highlights: [
          highlight(
            "highlight-navigation-3",
            "session-mobile-navigation",
            "Mobile navigation interview",
            "Aisha",
            "8:12",
            "I expected this menu to describe where I was going, not the action it performs.",
          ),
          highlight(
            "highlight-navigation-4",
            "session-mobile-navigation",
            "Mobile navigation interview",
            "Aisha",
            "21:04",
            "The wording changes between screens, so I have to relearn it.",
          ),
        ],
        sessionId: "session-mobile-navigation",
        sessionTitle: "Mobile navigation interview",
      },
    ],
    id: "code-navigation-terminology",
    knowledgeItemCount: 5,
    latestEvidenceAt: "2026-07-24T14:30:00Z",
    latestEvidenceLabel: "2 days ago",
    name: "Navigation terminology",
  },
  {
    acceptedHighlightCount: 9,
    description: "Participants needed clear focus and completion feedback throughout workflows.",
    eligibleSessionCount: 3,
    evidenceGroups: [
      {
        highlights: [
          highlight(
            "highlight-focus-1",
            "session-checkout",
            "Checkout usability test",
            "Robert",
            "6:56",
            "The focus ring is visible. That is good.",
          ),
        ],
        sessionId: "session-checkout",
        sessionTitle: "Checkout usability test",
      },
    ],
    id: "code-focus-feedback",
    knowledgeItemCount: 3,
    latestEvidenceAt: "2026-07-21T09:00:00Z",
    latestEvidenceLabel: "5 days ago",
    name: "Focus feedback",
  },
  {
    acceptedHighlightCount: 6,
    description: "Researchers expected failures to preserve context and provide a clear next action.",
    eligibleSessionCount: 2,
    evidenceGroups: [
      {
        highlights: [
          highlight(
            "highlight-error-1",
            "session-mobile-navigation",
            "Mobile navigation interview",
            "Aisha",
            "27:43",
            "I pressed Escape. It closed, but focus went to the top of the page. I lost my row.",
          ),
        ],
        sessionId: "session-mobile-navigation",
        sessionTitle: "Mobile navigation interview",
      },
    ],
    id: "code-error-recovery",
    knowledgeItemCount: 2,
    latestEvidenceAt: "2026-07-19T17:15:00Z",
    latestEvidenceLabel: "1 week ago",
    name: "Error recovery",
  },
  {
    acceptedHighlightCount: 5,
    description: "Participants needed confirmation before destructive changes were committed.",
    eligibleSessionCount: 3,
    evidenceGroups: [],
    id: "code-confirmation",
    knowledgeItemCount: 2,
    latestEvidenceAt: "2026-07-25T10:00:00Z",
    latestEvidenceLabel: "1 day ago",
    name: "Confirmation and reversibility",
  },
  {
    acceptedHighlightCount: 4,
    description: "Status labels needed to explain progress without relying on color alone.",
    eligibleSessionCount: 2,
    evidenceGroups: [],
    id: "code-status-language",
    knowledgeItemCount: 1,
    latestEvidenceAt: "2026-07-16T12:00:00Z",
    latestEvidenceLabel: "1 week ago",
    name: "Status language",
  },
  {
    acceptedHighlightCount: 3,
    description: "Participants expected keyboard focus to return to the action that opened an overlay.",
    eligibleSessionCount: 2,
    evidenceGroups: [],
    id: "code-focus-restoration",
    knowledgeItemCount: 1,
    latestEvidenceAt: "2026-07-14T15:00:00Z",
    latestEvidenceLabel: "2 weeks ago",
    name: "Focus restoration",
  },
  {
    acceptedHighlightCount: 2,
    description: "Dense tables increased navigation effort for keyboard users.",
    eligibleSessionCount: 1,
    evidenceGroups: [],
    id: "code-table-navigation",
    knowledgeItemCount: 1,
    latestEvidenceAt: "2026-07-12T11:00:00Z",
    latestEvidenceLabel: "2 weeks ago",
    name: "Table navigation",
  },
  {
    acceptedHighlightCount: 1,
    description: "Participants wanted concise help text close to unfamiliar controls.",
    eligibleSessionCount: 1,
    evidenceGroups: [],
    id: "code-contextual-help",
    knowledgeItemCount: 1,
    latestEvidenceAt: "2026-07-10T08:30:00Z",
    latestEvidenceLabel: "2 weeks ago",
    name: "Contextual help",
  },
];
